global:
  scrape_interval: 1s


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [
        "localhost:8700",
        "localhost:8701",
        "192.168.31.230:8700"
      ]